from __future__ import annotations

from typing import Any


TOOL_SPECS: list[dict] = [
    {"name": "powershell", "args": {"command": "string"}, "purpose": "Run a constrained PowerShell command in the harness workspace."},
    {"name": "wsl_status", "args": {}, "purpose": "Check whether WSL is installed and list available Linux distributions."},
    {"name": "wsl_probe", "args": {"distro": "string"}, "purpose": "Run a read-only WSL diagnostics probe for workspace mapping and Linux runtime basics."},
    {"name": "wsl", "args": {"command": "string", "distro": "string"}, "purpose": "Run a constrained Linux shell command through WSL inside the harness workspace when WSL is available."},
    {"name": "project_probe", "args": {"path": "string"}, "purpose": "Inspect a workspace project before running it: detected stack, isolation hints, common files, scripts, and default port availability."},
    {"name": "port_check", "args": {"port": "number"}, "purpose": "Check whether a localhost TCP port is already occupied and return listener details when available."},
    {"name": "find_free_port", "args": {"start": "number", "end": "number"}, "purpose": "Find an available localhost TCP port in a bounded range."},
    {"name": "tool_versions", "args": {}, "purpose": "Report installed versions for core local setup tools without installing anything."},
    {"name": "python_venv", "args": {"venv_path": "string", "requirements": "string", "install": "boolean"}, "purpose": "Create or reuse an isolated Python virtual environment inside the harness workspace."},
    {"name": "python_install", "args": {"path": "string", "venv_path": "string", "requirements": "string", "create_venv": "boolean"}, "purpose": "Install Python requirements into a workspace virtual environment through a structured, bounded wrapper."},
    {"name": "node_install", "args": {"path": "string", "package_manager": "string", "frozen": "boolean", "production": "boolean"}, "purpose": "Install Node project dependencies from package metadata through an allowlisted package-manager wrapper."},
    {"name": "start_process", "args": {"command": "string", "name": "string", "path": "string", "venv_path": "string", "port": "number", "wait_seconds": "number"}, "purpose": "Start a long-running dev server from an optional project subdirectory (path) with an optional venv on PATH, wait until the expected port listens or the process exits, then report readiness with stdout/stderr evidence. ok=true means the app is actually serving, not merely spawned."},
    {"name": "process_status", "args": {"pid": "number", "stdout_log": "string", "stderr_log": "string"}, "purpose": "Check whether a background process is still running and read recent stdout/stderr log tails."},
    {"name": "stop_process", "args": {"pid": "number"}, "purpose": "Stop a background process started by this harness (including its child processes)."},
    {"name": "list_processes", "args": {}, "purpose": "List background processes started by this harness with their liveness and log paths."},
    {"name": "screen_capture", "args": {"monitor": "number"}, "purpose": "Capture the screen to a PNG artifact. The image is attached to your next model turn so you can see it. Use before and after computer_* input actions."},
    {"name": "computer_click", "args": {"x": "number", "y": "number", "button": "string", "double": "boolean"}, "purpose": "Click at screen coordinates (button: left/right/middle). Take a screen_capture first to find the target coordinates."},
    {"name": "computer_move", "args": {"x": "number", "y": "number"}, "purpose": "Move the mouse cursor to screen coordinates."},
    {"name": "computer_type", "args": {"text": "string"}, "purpose": "Type literal text into the currently focused window."},
    {"name": "computer_type_at", "args": {"x": "number", "y": "number", "text": "string", "clear": "boolean", "submit": "boolean"}, "purpose": "Click coordinates, wait for focus, then type text in ONE step (clear=true wipes existing text first, submit=true presses Enter after). Prefer this over separate click+type: it prevents typing before the field is focused. Read x/y from the screen_capture grid."},
    {"name": "open_app", "args": {"name": "string"}, "purpose": "Launch a known desktop app by name (notepad, calculator, paint, explorer, control panel, cmd, powershell, wordpad, task manager). Use this instead of pixel-clicking through the Start menu; then screen_capture to see the app window."},
    {"name": "computer_key", "args": {"keys": "string"}, "purpose": "Press a key or chord in the focused window, e.g. 'enter', 'ctrl+s', 'alt+tab'."},
    {"name": "computer_scroll", "args": {"amount": "number", "x": "number", "y": "number"}, "purpose": "Scroll the mouse wheel (positive = up, negative = down), optionally after moving to x/y."},
    {"name": "list_windows", "args": {}, "purpose": "List visible desktop windows with titles and geometry."},
    {"name": "focus_window", "args": {"title": "string"}, "purpose": "Bring the first window whose title matches to the foreground."},
    {"name": "python", "args": {"code": "string"}, "purpose": "Run a short Python snippet in the harness workspace."},
    {"name": "read_file", "args": {"path": "string", "start_line": "number", "line_count": "number"}, "purpose": "Read a file under the harness workspace (or a saved Neo .log path). Pass start_line (1-based) and line_count to read a numbered window of a big file. PDF, Word (.docx), and Excel (.xlsx) files are auto-extracted to readable text."},
    {"name": "write_file", "args": {"path": "string", "content": "string", "force": "boolean"}, "purpose": "Write a file under the harness workspace; parent directories are created automatically. Content that would break .py/.json syntax is rejected with the parse error (force=true overrides for intentionally invalid files)."},
    {"name": "append_file", "args": {"path": "string", "content": "string"}, "purpose": "Append text to a file under the harness workspace; parent directories are created automatically."},
    {"name": "edit_file", "args": {"path": "string", "old": "string", "new": "string", "replace_all": "boolean", "force": "boolean"}, "purpose": "Replace exact text in a workspace file. The old text must match exactly once (add surrounding context) or pass replace_all=true. Edits that would break .py/.json syntax are rejected with the parse error."},
    {"name": "make_dir", "args": {"path": "string"}, "purpose": "Create a directory under the harness workspace."},
    {"name": "move_path", "args": {"source": "string", "destination": "string", "overwrite": "boolean"}, "purpose": "Move a file or directory within the harness workspace after both paths are validated."},
    {"name": "copy_path", "args": {"source": "string", "destination": "string", "recursive": "boolean"}, "purpose": "Copy a file (or a directory with recursive=true) within the harness workspace. Refuses to overwrite an existing destination."},
    {"name": "delete_path", "args": {"path": "string", "recursive": "boolean"}, "purpose": "Delete a file or directory inside the harness workspace (recursive=true for a non-empty directory). Safe, sandboxed deletion; use this instead of shell remove commands."},
    {"name": "file_info", "args": {"path": "string"}, "purpose": "Return size, modified time, and type for a workspace path."},
    {"name": "tree", "args": {"path": "string", "max_depth": "number"}, "purpose": "Return a bounded directory tree under the harness workspace."},
    {"name": "list_files", "args": {"path": "string"}, "purpose": "List files under the harness workspace."},
    {"name": "search_files", "args": {"path": "string", "pattern": "glob", "max_results": "number"}, "purpose": "Find files under the harness workspace by glob pattern."},
    {"name": "grep", "args": {"path": "string", "pattern": "regex", "case_sensitive": "boolean", "max_results": "number"}, "purpose": "Search text files under the harness workspace and return matching lines."},
    {"name": "python_symbols", "args": {"path": "string"}, "purpose": "Parse a Python file and list classes, functions, and imports."},
    {"name": "json_validate", "args": {"text": "string"}, "purpose": "Validate and summarize JSON text."},
    {"name": "image_info", "args": {"path": "string"}, "purpose": "Read bounded metadata and dimensions for an image file under the harness workspace."},
    {"name": "pdf_info", "args": {"path": "string"}, "purpose": "Read bounded structural metadata from a PDF file under the harness workspace."},
    {"name": "pdf_text_extract", "args": {"path": "string", "page_limit": "number", "char_limit": "number"}, "purpose": "Extract bounded text from a workspace PDF using optional libraries or a built-in best-effort parser."},
    {"name": "syntax_check", "args": {"path": "string", "max_files": "number"}, "purpose": "Check Python, JSON, and JavaScript syntax for a workspace file or bounded directory scan."},
    {"name": "run_tests", "args": {"runner": "string", "path": "string", "maxfail": "number", "timeout_seconds": "number"}, "purpose": "Run an allowlisted test runner such as pytest against a validated workspace path with bounded output."},
    {"name": "system_security_audit", "args": {"scope": "string"}, "purpose": "Run a read-only bounded audit of the current host OS security posture without exposing secrets."},
    {"name": "secrets_scan", "args": {"path": "string", "max_files": "number"}, "purpose": "Scan workspace text files for likely hardcoded secrets and return redacted evidence only."},
    {"name": "dependency_audit", "args": {"path": "string", "ecosystem": "string"}, "purpose": "Run bounded Python/Node dependency security audit probes when project metadata and tools are available."},
    {"name": "web_search", "args": {"query": "string"}, "purpose": "Search the public web and return compact result candidates."},
    {"name": "web_fetch", "args": {"url": "string"}, "purpose": "Fetch a public web page and return readable text plus links."},
    {"name": "web_links", "args": {"url": "string"}, "purpose": "Fetch a public web page and extract links."},
    {"name": "scrape_page", "args": {"url": "string"}, "purpose": "Scrape a public page into title, headings, readable text, links, and extracted price-like values."},
    {"name": "scrape_urls", "args": {"urls": "array"}, "purpose": "Scrape several public URLs and return compact page summaries."},
    {"name": "research_web", "args": {"query": "string", "max_pages": "number"}, "purpose": "Search the web, open top candidate pages, scrape them, and return source-backed findings."},
    {"name": "http_head", "args": {"url": "string"}, "purpose": "Inspect public URL headers without downloading the body."},
    {"name": "http_get", "args": {"url": "string"}, "purpose": "Fetch a small HTTP/HTTPS response for integration checks."},
    {"name": "app_healthcheck", "args": {"url": "string", "path": "string", "checks": "array"}, "purpose": "Prove a served app actually works: checks the root page, every css/js it references (status + MIME), missing Node dependencies (pass the project path), and your declared acceptance checks [{method, path, body, expect_status, expect_contains}]. Run it after starting or changing an app and fix every FAIL line; a feature is only done when a passing check covers it."},
    {"name": "open_browser", "args": {"url": "string"}, "purpose": "Open a safe http:// or https:// URL in the user's default browser for manual UI verification."},
    {"name": "open_vscode", "args": {"path": "string"}, "purpose": "Open the harness workspace or a workspace file in VS Code."},
    {"name": "download_url", "args": {"url": "string", "path": "string", "max_bytes": "number"}, "purpose": "Download a public URL into the harness workspace."},
    {"name": "sql_query", "args": {"query": "string"}, "purpose": "Run a read-only SELECT/SHOW/DESCRIBE/EXPLAIN query against the harness database."},
    {"name": "git_status", "args": {}, "purpose": "Run git status in the harness workspace if it is a git repository."},
    {"name": "git_diff", "args": {"path": "string"}, "purpose": "Return a bounded git diff for the harness workspace."},
    {"name": "context_read", "args": {"limit": "number"}, "purpose": "Read recent shared context rows from the harness database."},
    {"name": "context_write", "args": {"content": "string", "importance": "number"}, "purpose": "Write a note into shared context for all agents."},
    {"name": "list_agents", "args": {}, "purpose": "List known harness agents and their statuses."},
    {"name": "project_brief_set", "args": {"goal": "string", "stack": "string", "conventions": "string"}, "purpose": "Set the shared project brief the whole team builds against: the goal, the ONE chosen stack (framework + database + language), and conventions (ports, directory layout, naming). Set this FIRST when several agents work on one app so nobody picks a different framework, database, or port."},
    {"name": "project_task_add", "args": {"title": "string", "owner": "string", "depends_on": "string", "deliverable": "string"}, "purpose": "Add a task to the shared project board with an owner (which role/agent), dependencies (task ids or titles that must finish first), and a concrete deliverable. Use this to divide work across agents so nobody duplicates or skips a piece."},
    {"name": "project_task_update", "args": {"task_id": "number", "status": "string", "notes": "string"}, "purpose": "Update a shared task's status (todo | in_progress | done | blocked) and notes. Mark your task in_progress when you start and done when its deliverable is verified, so the team sees real progress."},
    {"name": "project_status", "args": {}, "purpose": "Read the shared project plan: the brief (goal, stack, conventions) and the task board with owners, dependencies, and statuses. Consult this before acting so you build to the same stack and do not redo another agent's work."},
    {"name": "metrics_snapshot", "args": {}, "purpose": "Return database counts and latest eval/run metrics."},
    {"name": "tool_catalog", "args": {}, "purpose": "Return this full tool catalog as JSON for tool discovery."},
    {"name": "write_artifact", "args": {"name": "string", "content": "string"}, "purpose": "Write a diagnostic artifact under artifacts/tool_outputs."},
]

TOOL_DEFAULTS: dict[str, Any] = {
    "category": "workspace",
    "risk": "low",
    "writes_workspace": False,
    "requires_network": False,
    "platforms": ["windows", "linux", "macos"],
}

TOOL_METADATA: dict[str, dict[str, Any]] = {
    "powershell": {"category": "shell", "risk": "high", "writes_workspace": True, "platforms": ["windows"]},
    "wsl_status": {"category": "diagnostics", "platforms": ["windows"]},
    "wsl_probe": {"category": "diagnostics", "platforms": ["windows", "wsl"]},
    "wsl": {"category": "shell", "risk": "high", "writes_workspace": True, "platforms": ["windows", "wsl"]},
    "project_probe": {"category": "diagnostics"},
    "port_check": {"category": "diagnostics"},
    "find_free_port": {"category": "diagnostics"},
    "tool_versions": {"category": "setup"},
    "python_venv": {"category": "setup", "risk": "medium", "writes_workspace": True},
    "python_install": {"category": "setup", "risk": "medium", "writes_workspace": True, "requires_network": True},
    "node_install": {"category": "setup", "risk": "medium", "writes_workspace": True, "requires_network": True},
    "start_process": {"category": "runtime", "risk": "medium", "writes_workspace": True, "platforms": ["windows", "linux", "macos"]},
    "process_status": {"category": "runtime"},
    "stop_process": {"category": "runtime", "risk": "medium"},
    "list_processes": {"category": "runtime"},
    "screen_capture": {"category": "computer", "risk": "medium", "platforms": ["windows"]},
    "computer_click": {"category": "computer", "risk": "high", "platforms": ["windows"]},
    "computer_move": {"category": "computer", "risk": "medium", "platforms": ["windows"]},
    "computer_type": {"category": "computer", "risk": "high", "platforms": ["windows"]},
    "computer_type_at": {"category": "computer", "risk": "high", "platforms": ["windows"]},
    "open_app": {"category": "computer", "risk": "high", "platforms": ["windows"]},
    "computer_key": {"category": "computer", "risk": "high", "platforms": ["windows"]},
    "computer_scroll": {"category": "computer", "risk": "medium", "platforms": ["windows"]},
    "list_windows": {"category": "computer", "platforms": ["windows"]},
    "focus_window": {"category": "computer", "risk": "medium", "platforms": ["windows"]},
    "python": {"category": "shell", "risk": "medium", "writes_workspace": True},
    "write_file": {"risk": "medium", "writes_workspace": True},
    "append_file": {"risk": "medium", "writes_workspace": True},
    "edit_file": {"risk": "medium", "writes_workspace": True},
    "make_dir": {"risk": "medium", "writes_workspace": True},
    "move_path": {"risk": "high", "writes_workspace": True},
    "copy_path": {"risk": "medium", "writes_workspace": True},
    "delete_path": {"risk": "high", "writes_workspace": True},
    "file_info": {"category": "diagnostics"},
    "tree": {"category": "diagnostics"},
    "list_files": {"category": "diagnostics"},
    "search_files": {"category": "diagnostics"},
    "grep": {"category": "diagnostics"},
    "python_symbols": {"category": "diagnostics"},
    "json_validate": {"category": "diagnostics"},
    "image_info": {"category": "diagnostics"},
    "pdf_info": {"category": "diagnostics"},
    "pdf_text_extract": {"category": "diagnostics"},
    "syntax_check": {"category": "diagnostics"},
    "run_tests": {"category": "diagnostics", "risk": "medium", "writes_workspace": True},
    "system_security_audit": {"category": "security", "risk": "medium", "platforms": ["windows", "linux", "macos"]},
    "secrets_scan": {"category": "security", "risk": "medium"},
    "dependency_audit": {"category": "security", "risk": "medium", "requires_network": True},
    "web_search": {"category": "network", "requires_network": True},
    "web_fetch": {"category": "network", "requires_network": True},
    "web_links": {"category": "network", "requires_network": True},
    "scrape_page": {"category": "network", "requires_network": True},
    "scrape_urls": {"category": "network", "requires_network": True},
    "research_web": {"category": "network", "requires_network": True},
    "http_head": {"category": "network", "requires_network": True},
    "http_get": {"category": "network", "requires_network": True},
    "app_healthcheck": {"category": "diagnostics", "requires_network": True},
    "open_browser": {"category": "external"},
    "open_vscode": {"category": "external"},
    "download_url": {"category": "network", "risk": "medium", "writes_workspace": True, "requires_network": True},
    "sql_query": {"category": "diagnostics", "risk": "medium"},
    "git_status": {"category": "diagnostics"},
    "git_diff": {"category": "diagnostics"},
    "context_read": {"category": "coordination"},
    "context_write": {"category": "coordination", "risk": "medium"},
    "list_agents": {"category": "coordination"},
    "project_brief_set": {"category": "coordination", "risk": "medium"},
    "project_task_add": {"category": "coordination", "risk": "medium"},
    "project_task_update": {"category": "coordination", "risk": "medium"},
    "project_status": {"category": "coordination"},
    "metrics_snapshot": {"category": "diagnostics"},
    "tool_catalog": {"category": "diagnostics"},
    "write_artifact": {"category": "diagnostics", "writes_workspace": False},
}


def describe_tools() -> list[dict]:
    enriched: list[dict] = []
    for item in TOOL_SPECS:
        entry = dict(item)
        entry.update(TOOL_DEFAULTS)
        entry.update(TOOL_METADATA.get(str(item.get("name")), {}))
        enriched.append(entry)
    return enriched
